In [1]:
import os
os.getcwd()

'C:\\Users\\a'

In [3]:
import numpy as np
x=np.array([1,2,4])
print(x)
m = np.array([[7, 8, 9],[1,2,3]])
m

[1 2 4]


array([[7, 8, 9],
       [1, 2, 3]])

In [5]:
m.shape

(2, 3)

In [3]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [4]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [5]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [6]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [7]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.ones?

In [9]:
import os
os.getcwd()

'C:\\Users\\a'

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
y = np.array([4, 5, 6])
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [14]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [16]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [19]:
x=np.array([1,2,3])
print(x)
y = np.array([4, 5, 6])
y

[1 2 3]


array([4, 5, 6])

In [20]:
print(x+y)

[5 7 9]


In [21]:
print(x-y)
print(x/y)
print(x*y)
print(x**2)

[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[1 4 9]


In [22]:
print(x.dot(y))


32


In [23]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array
z

2


array([[ 4,  5,  6],
       [16, 25, 36]])

In [24]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [25]:
z.shape

(2, 3)

In [26]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [27]:
z.T.shape

(3, 2)

In [28]:
z.dtype

dtype('int32')

In [29]:
z = z.astype('f')
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

In [30]:
a = np.array([-4, -2, 1, 3, 5])

In [31]:
a.sum()

3

In [32]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [33]:
s[-4:]

array([ 81, 100, 121, 144])

In [34]:
#indicate step-size. array[start:stop:stepsize]
s[5::-2]

array([25,  9,  1])

In [35]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [51]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [52]:
r[3, 3:6]

array([21, 22, 23])

In [54]:
r[:2, :-4]

array([[0, 1],
       [6, 7]])

In [55]:
r>30

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True]])

In [39]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [40]:
r[r > 30]=30

In [41]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [42]:
r_copy = r.copy()

In [43]:
r_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [44]:
r_copy[:] = 10

In [45]:
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [46]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [47]:
# 4 by 3 array of random numbers 0-9
test = np.random.randint(0, 10, (4,3))
test

array([[2, 4, 8],
       [7, 1, 1],
       [2, 6, 7],
       [3, 9, 8]])

In [48]:
test = np.random.randint(0, 10,5)
test

array([4, 4, 3, 7, 0])

In [49]:
test2 = test**2
print(test2)
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[16 16  9 49  0]
4 + 16 = 20
4 + 16 = 20
3 + 9 = 12
7 + 49 = 56
0 + 0 = 0


In [56]:
test = np.random.randint(0, 10, (4,3))
test

array([[0, 3, 0],
       [3, 7, 1],
       [9, 5, 3],
       [0, 7, 8]])

In [57]:
for row in test:
    print(row)

[0 3 0]
[3 7 1]
[9 5 3]
[0 7 8]


In [58]:
for i in range(len(test)):
    print(test[i])

[0 3 0]
[3 7 1]
[9 5 3]
[0 7 8]


In [59]:
a=np.array([1.0,'23',23])
a

array(['1.0', '23', '23'], dtype='<U32')

In [4]:
np.fliplr?